### ISSUE TITLE
CountrySchema.callingCode does not get populated

### ISSUE THREAD

**Issue by illesg** [taxamo/taxamo-java#1]
When creating a transaction with a forced country code (e.g. "HU"), the `transaction.getCountries().getForced()` function returns the right `CountrySchema` object, but the `callingCode` string list is empty. 
While debugging i noticed that the REST api returns the right calling codes, but it does not get parsed by the java client.

**Comment by tlipski** [comment]
Please see if 2b5e0143b4a7f233c8fa7b085f20c3eb838abe2c and c62ae54398f02b9be9f95737abbfad7af1a1b8b7 solve the issue for you

**Comment by tlipski** [comment]
please re-open the issue if it still persists with 1.1.0 version
